package com.idearworld.model;

import java.util.Date;

public class Idears {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Idears.idear_id
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    private Integer idearId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Idears.user_id
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Idears.title
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Idears.problem
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Idears.solution
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    private String solution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Idears.is_public
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    private Integer isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Idears.image_file
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    private String imageFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Idears.link
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Idears.create_date
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Idears.idear_id
     *
     * @return the value of Idears.idear_id
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public Integer getIdearId() {
        return idearId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Idears.idear_id
     *
     * @param idearId the value for Idears.idear_id
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public void setIdearId(Integer idearId) {
        this.idearId = idearId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Idears.user_id
     *
     * @return the value of Idears.user_id
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Idears.user_id
     *
     * @param userId the value for Idears.user_id
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Idears.title
     *
     * @return the value of Idears.title
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Idears.title
     *
     * @param title the value for Idears.title
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Idears.problem
     *
     * @return the value of Idears.problem
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Idears.problem
     *
     * @param problem the value for Idears.problem
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Idears.solution
     *
     * @return the value of Idears.solution
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public String getSolution() {
        return solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Idears.solution
     *
     * @param solution the value for Idears.solution
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public void setSolution(String solution) {
        this.solution = solution == null ? null : solution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Idears.is_public
     *
     * @return the value of Idears.is_public
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public Integer getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Idears.is_public
     *
     * @param isPublic the value for Idears.is_public
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public void setIsPublic(Integer isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Idears.image_file
     *
     * @return the value of Idears.image_file
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public String getImageFile() {
        return imageFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Idears.image_file
     *
     * @param imageFile the value for Idears.image_file
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public void setImageFile(String imageFile) {
        this.imageFile = imageFile == null ? null : imageFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Idears.link
     *
     * @return the value of Idears.link
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Idears.link
     *
     * @param link the value for Idears.link
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Idears.create_date
     *
     * @return the value of Idears.create_date
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Idears.create_date
     *
     * @param createDate the value for Idears.create_date
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}