package com.idearworld.dao;

import com.idearworld.model.Idears;
import com.idearworld.model.IdearsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IdearsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    int countByExample(IdearsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    int deleteByExample(IdearsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    int deleteByPrimaryKey(Integer idearId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    int insert(Idears record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    int insertSelective(Idears record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    List<Idears> selectByExample(IdearsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    Idears selectByPrimaryKey(Integer idearId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    int updateByExampleSelective(@Param("record") Idears record, @Param("example") IdearsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    int updateByExample(@Param("record") Idears record, @Param("example") IdearsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    int updateByPrimaryKeySelective(Idears record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Idears
     *
     * @mbggenerated Sun Aug 26 16:31:51 CST 2012
     */
    int updateByPrimaryKey(Idears record);
}