package com.idearworld.model;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.idear_id
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    private Integer idearId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_type
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    private Integer commentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_date
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    private Date commentDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.idear_id
     *
     * @return the value of comment.idear_id
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public Integer getIdearId() {
        return idearId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.idear_id
     *
     * @param idearId the value for comment.idear_id
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public void setIdearId(Integer idearId) {
        this.idearId = idearId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_type
     *
     * @return the value of comment.comment_type
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public Integer getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_type
     *
     * @param commentType the value for comment.comment_type
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment
     *
     * @return the value of comment.comment
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment
     *
     * @param comment the value for comment.comment
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_date
     *
     * @return the value of comment.comment_date
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_date
     *
     * @param commentDate the value for comment.comment_date
     *
     * @mbggenerated Tue Sep 04 16:26:19 GMT+08:00 2012
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }
}